/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package note;

/**
 *
 * @author Michelle Alvarado
 */
public class NoteEditor extends javax.swing.JFrame {

    /**
     * Creates new form NoteEditor
     */
    public NoteEditor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noteMainContainer = new javax.swing.JPanel();
        noteTextArea = new java.awt.TextArea();
        noteHeader = new javax.swing.JPanel();
        tooltipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        noteMainContainer.setBackground(new java.awt.Color(204, 232, 217));

        noteTextArea.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        noteTextArea.setMaximumSize(new java.awt.Dimension(100, 80));

        noteHeader.setBackground(new java.awt.Color(90, 129, 158));
        noteHeader.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Note Editor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        tooltipButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tooltipButton.setForeground(new java.awt.Color(255, 255, 255));
        tooltipButton.setText("?");
        tooltipButton.setBorderPainted(false);
        tooltipButton.setContentAreaFilled(false);
        tooltipButton.setFocusPainted(false);
        tooltipButton.setFocusable(false);
        tooltipButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout noteHeaderLayout = new javax.swing.GroupLayout(noteHeader);
        noteHeader.setLayout(noteHeaderLayout);
        noteHeaderLayout.setHorizontalGroup(
            noteHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noteHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tooltipButton))
        );
        noteHeaderLayout.setVerticalGroup(
            noteHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tooltipButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tooltipButton.setToolTipText("Press 'CTRL + X' to exit");

        javax.swing.GroupLayout noteMainContainerLayout = new javax.swing.GroupLayout(noteMainContainer);
        noteMainContainer.setLayout(noteMainContainerLayout);
        noteMainContainerLayout.setHorizontalGroup(
            noteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noteTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(noteHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        noteMainContainerLayout.setVerticalGroup(
            noteMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noteMainContainerLayout.createSequentialGroup()
                .addComponent(noteHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(noteTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noteMainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noteMainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoteEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoteEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoteEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoteEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoteEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel noteHeader;
    private javax.swing.JPanel noteMainContainer;
    public java.awt.TextArea noteTextArea;
    private javax.swing.JButton tooltipButton;
    // End of variables declaration//GEN-END:variables
}
